<?php

namespace AppBundle\Repository;

use AppBundle\Entity\ListItems;
use Doctrine\ORM\EntityRepository;
use Exception;
/**
 * ListItemsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListItemsRepository extends EntityRepository
{
    public function getAll()
    {
        $em = $this->getEntityManager();

        $em->getFilters()->disable('user_filter');

        return $this->findAll();
    }

    public function save(ListItems $listItems)
    {
        $entityManager = $this->getEntityManager();

        $entityManager->persist($listItems);

        $entityManager->flush();
    }

    public function destroy($id)
    {
        $em = $this->getEntityManager();

        try {
            $em->remove(
                $em->getReference('AppBundle:ListItems', $id)
            );

            $em->flush();
        } catch (Exception $e) {
            throw new Exception($e->getMessage());
        }
    }
}
