<?php

namespace AppBundle\Repository;

use AppBundle\Entity\ListItems;
use AppBundle\Repository\Common\Persist;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Common\Persistence\ManagerRegistry;
use Exception;
/**
 * ListItemsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListItemsRepository extends ServiceEntityRepository
{
    use Persist;

    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, ListItems::class);
    }

    public function getAll()
    {
        $em = $this->getEntityManager();

        $em->getFilters()->disable('user_filter');

        return $this->findAll();
    }

    public function destroy($id)
    {
        $em = $this->getEntityManager();

        try {
            $em->remove(
                $em->getReference('AppBundle:ListItems', $id)
            );

            $em->flush();
        } catch (Exception $e) {
            throw new Exception($e->getMessage());
        }
    }
}
