<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;
use AppBundle\Repository\Common\Persist;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Common\Persistence\ManagerRegistry;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends ServiceEntityRepository
{
    use Persist;

    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, User::class);
    }

    public function update()
    {
        $em = $this->getEntityManager();
        $em->flush();
    }
}
